### ISSUE TITLE
Support latest pathways for freshmen cohort in V1.0 website

### ISSUE THREAD

**Issue by wangj55** [Phon1209/HassPathwaysV2.0#1]
Latest pathways structure is not supported on the V1.0 website. When we work on the 2.0, we want the freshmen to have something to use on V1.0.

We need to scrap [latest pathways](https://catalog.rpi.edu/content.php?catoid=26&navoid=669)(changed in 2023-2024), and use course data from Quatalog. Scripts are in V1.0 repo and we can use that.

[Quatalog](https://quatalog.com/) seems to have the latest data, its repo is https://github.com/quatalog/data. We can probably use the data here.

Latest pathways and courses should be placed in `HASSPathways/frontend/src/data/json/2023-2024/`

We might also need to support different pathway categories for different cohorts.

**Comment by danielsodium** [comment]
Finished
