### ISSUE TITLE
[Improve] Apply deboucing to search bars

### ISSUE THREAD

**Issue by wangj55** [Phon1209/HassPathwaysV2.0#13]
Currently, every time the user types a letter in the search bar, a request is sent with the input as a search param. So typing a single word fires TOO many requests, and it's significantly impacting the component's render. We want to improve this.

Debouncing ensures that a function won’t execute until X milliseconds after the last time it was triggered.

We need to take care of:
1. pathway search bar
2. course search bar

Take a look at [lodash's debounce()](https://lodash.com/docs/4.17.15#debounce) or create our own.

**Comment by Phon1209** [comment]
I believe this has been implemented as deferredValue using useDeferredValue hook from React.

**Comment by wangj55** [comment]
> I believe this has been implemented as deferredValue using useDeferredValue hook from React.

Thanks! I'll take a look on useDeferredValue.

**Comment by wangj55** [comment]
After some research, I found that `useDeferredValue` is best for optimizing rerendering, but deboucing can still help reduce the number of network requests in our app. I think we can use both together.
